# Generated by Django 4.0.5 on 2022-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
