# Generated by Django 4.0.5 on 2022-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_remove_tutor_email_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='contact',
        ),
    ]
