# Generated by Django 4.0.5 on 2022-06-21 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_remove_tutor_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
