# Generated by Django 4.0.5 on 2022-06-22 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_alter_tutor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_poster',
            new_name='coursePoster',
        ),
    ]
